# ./docker-compose.yml
version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    user: "${USER_ID}:${GROUP_ID}"
    command: ./entrypoint.sh
    # environment:
    #   REDIS_URL: redis://redis:6379/
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
